# Generated by Django 5.0.6 on 2024-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='d_Picture',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_Picture',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='images/'),
        ),
    ]
