# Generated by Django 5.0.6 on 2024-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin', '0002_alter_doctor_d_picture_alter_patient_p_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='d_Pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_Pincode',
            field=models.IntegerField(),
        ),
    ]
